import type { VisualTemplateDefinition } from "./shared";
import { template } from "./shared";

export const ECONOMICS_STATISTICS_VISUAL_TEMPLATES: VisualTemplateDefinition[] = [
	template({
		id: "economics-demand-supply",
		title: "Demand and supply curve",
		description: "Market curve with equilibrium and policy marks.",
		subjects: ["Economics", "Business Studies"],
		topicTags: ["demand", "supply", "equilibrium", "price ceiling", "price floor", "market"],
		gradeBands: ["11-12"],
		kind: "economics_curve",
		priority: "essential",
		slotContract: {
			requiredSlots: ["curves", "axisLabels"],
			optionalSlots: ["marks", "equilibriumPoint", "policyLine"],
			constraints: ["Caption must not state the interpretation being assessed."],
		},
	}),
	template({
		id: "statistics-chart-stimulus",
		title: "Statistics chart",
		description: "Histogram, bar, line, scatter, pie, frequency polygon, ogive, or box chart.",
		subjects: ["Statistics", "Economics", "Business Studies", "Geography", "Social Science"],
		topicTags: ["statistics", "frequency", "histogram", "bar chart", "line graph", "ogive", "box plot", "data"],
		gradeBands: ["6-8", "9-10", "11-12"],
		kind: "statistics_chart",
		priority: "essential",
		slotContract: {
			requiredSlots: ["subKind", "data"],
			optionalSlots: ["axisLabels", "legend", "callouts"],
			constraints: ["Chart data must match values used by the answer key."],
		},
	}),
	template({
		id: "economics-9-palampur-production-table",
		title: "Palampur factors-of-production table",
		description: "Tabular stimulus for Palampur village data: cultivated/non-cultivated land, irrigation, capital, labour, facilities.",
		subjects: ["Economics", "Social Science"],
		topicTags: ["village palampur", "factors of production", "land", "labour", "physical capital", "human capital", "irrigation", "multiple cropping", "modern farming"],
		gradeBands: ["9-10"],
		kind: "data_table",
		priority: "essential",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption", "boldCells"],
			constraints: [
				"Row values must match the chapter's quantitative claims.",
				"Leave only the assessed cell blank.",
			],
		},
	}),
	template({
		id: "economics-9-poverty-ratio-chart",
		title: "Poverty ratio bar chart",
		description: "Bar or line chart of poverty ratios across years, social groups, or states for India.",
		subjects: ["Economics", "Social Science"],
		topicTags: ["poverty", "poverty line", "poverty ratio", "head count ratio", "social exclusion", "vulnerability", "scheduled caste", "scheduled tribe", "rural urban poverty"],
		gradeBands: ["9-10"],
		kind: "statistics_chart",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["subKind", "data"],
			optionalSlots: ["axisLabels", "callouts"],
			constraints: [
				"Bar values must match the cited NCERT poverty-ratio figures.",
				"Caption must not state the highest or lowest year when comparison is the question.",
			],
		},
	}),
	template({
		id: "economics-9-food-security-table",
		title: "Food availability and procurement table",
		description: "Tabular stimulus for Bengal rice production / PDS allocations / buffer-stock figures.",
		subjects: ["Economics", "Social Science"],
		topicTags: ["food security", "buffer stock", "public distribution system", "pds", "minimum support price", "bengal famine", "rice production", "ration shop"],
		gradeBands: ["9-10"],
		kind: "data_table",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption", "boldCells"],
			constraints: [
				"Year-wise totals must reconcile with the chapter when the question references availability.",
				"Caption must not state which year had the drastic decline.",
			],
		},
		fallbackKind: "statistics_chart",
	}),
	template({
		id: "economics-development-comparison-grade-10",
		title: "Development indicators comparison (Grade 10)",
		description: "Table comparing two or more countries / states on per-capita income, literacy, infant mortality, HDI rank, life expectancy.",
		subjects: ["Economics", "Social Science"],
		topicTags: ["development", "per capita income", "hdi", "human development", "literacy rate", "infant mortality", "life expectancy", "national income", "growth rate"],
		gradeBands: ["9-10"],
		kind: "data_table",
		priority: "essential",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption"],
			constraints: [
				"Columns should include at minimum the country/state name and the indicator the question asks about.",
				"Do not pre-rank or pre-classify the entities — the stem must drive interpretation.",
			],
		},
	}),
	template({
		id: "economics-sectors-chart-grade-10",
		title: "Sectors of Indian economy chart (Grade 10)",
		description: "Pie or bar chart of primary / secondary / tertiary share in GDP or employment for India over time.",
		subjects: ["Economics", "Social Science", "Statistics"],
		topicTags: ["sectors of the indian economy", "primary sector", "secondary sector", "tertiary sector", "service sector", "gva", "employment share", "gdp share"],
		gradeBands: ["9-10"],
		kind: "statistics_chart",
		priority: "essential",
		slotContract: {
			requiredSlots: ["subKind"],
			optionalSlots: ["xLabel", "yLabel"],
			constraints: [
				"Use `subKind: pie` for share-at-one-point-in-time, `subKind: bar` for cross-period comparison.",
				"Values must reconcile to ~100 % across the three sectors in a pie.",
			],
		},
	}),
	template({
		id: "economics-money-credit-flow-grade-10",
		title: "Money and credit flowchart (Grade 10)",
		description: "Flowchart of credit sources — formal (banks, cooperatives, RBI) vs. informal (moneylender, trader, friends).",
		subjects: ["Economics", "Social Science"],
		topicTags: ["money and credit", "formal credit", "informal credit", "bank", "moneylender", "cooperative", "self help group", "rbi", "collateral", "interest rate"],
		gradeBands: ["9-10"],
		kind: "flowchart",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["title", "nodes", "edges"],
			optionalSlots: [],
			constraints: [
				"Top node is 'Sources of Credit'; left branch is Formal, right branch is Informal.",
				"Outcome / interest-rate labels should not give away the answer when the question is about comparison.",
			],
		},
		fallbackKind: "data_table",
	}),
];
