import type { VisualTemplateDefinition } from "./shared";
import { template } from "./shared";

export const GEOGRAPHY_SOCIAL_SCIENCE_VISUAL_TEMPLATES: VisualTemplateDefinition[] = [
	template({
		id: "social-science-source-extract",
		title: "Source extract",
		description: "History, civics, economics, or geography source/case extract with line numbers.",
		subjects: ["Social Science", "History", "Civics", "Geography", "Business Studies"],
		topicTags: ["source", "extract", "case", "constitution", "history", "civics", "passage"],
		gradeBands: ["9-10", "11-12"],
		kind: "source_extract",
		priority: "essential",
		slotContract: {
			requiredSlots: ["lines"],
			optionalSlots: ["title", "source", "context"],
			constraints: ["Do not put interpretation or answers in alt text."],
		},
		fallbackKind: "english_passage",
	}),
	template({
		id: "social-science-map-location",
		title: "Map visual",
		description: "Map-based location, region, route, or thematic stimulus.",
		subjects: ["Geography", "Social Science", "History"],
		topicTags: ["map", "location", "state", "region", "river", "resource", "route", "climate"],
		gradeBands: ["6-8", "9-10", "11-12"],
		kind: "map_visual",
		priority: "essential",
		slotContract: {
			requiredSlots: ["scope", "regions", "title"],
			optionalSlots: ["mapStyle"],
			constraints: ["Every highlighted region must be named in alt text without revealing the answer."],
		},
		fallbackKind: "india_map",
	}),
	template({
		id: "history-timeline",
		title: "Timeline",
		description: "Chronological events with labelled dates and concise annotations.",
		subjects: ["History", "Social Science"],
		topicTags: ["timeline", "chronology", "movement", "event", "period", "dates"],
		gradeBands: ["6-8", "9-10", "11-12"],
		kind: "timeline",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["events", "title"],
			optionalSlots: ["axisLabel"],
			constraints: ["Events must be in chronological order unless the question asks students to reorder them."],
		},
	}),
	template({
		id: "geography-9-physical-features-map",
		title: "India physiographic divisions map",
		description: "India outline with one or more physiographic regions highlighted: Himalayas, Northern Plains, Peninsular Plateau, Coastal Plains, Islands.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["physical features", "himalayas", "northern plain", "peninsular plateau", "coastal plain", "purvachal", "physiographic divisions"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "essential",
		slotContract: {
			requiredSlots: ["highlightedStates"],
			optionalSlots: ["mapStyle"],
			constraints: [
				"Highlight only the regions referenced in the stem.",
				"Caption must not name the region when identification is the question.",
			],
		},
		fallbackKind: "map_visual",
	}),
	template({
		id: "geography-9-drainage-rivers-map",
		title: "India river drainage map",
		description: "India outline with named Himalayan or Peninsular rivers highlighted for basin-identification and source stems.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["drainage", "river", "himalayan rivers", "peninsular rivers", "ganga", "brahmaputra", "indus", "godavari", "krishna", "narmada", "tapi", "river basin", "tributary"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "essential",
		slotContract: {
			requiredSlots: ["highlightedStates"],
			optionalSlots: ["mapStyle"],
			constraints: [
				"Indicate the river course by highlighting the relevant states only.",
				"Caption must not name the river when identification is the question.",
			],
		},
		fallbackKind: "map_visual",
	}),
	template({
		id: "geography-9-climate-rainfall-map",
		title: "India monsoon and rainfall map",
		description: "India outline with monsoon-arrival regions or rainfall belts highlighted for climate stems.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["climate", "monsoon", "south west monsoon", "north east monsoon", "rainfall", "mawsynram", "cherrapunji", "loo", "kal baisakhi", "diurnal range"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["highlightedStates"],
			optionalSlots: ["mapStyle"],
			constraints: [
				"Highlight only the rainfall regions referenced in the stem.",
				"Caption must not state the rainfall figure being asked.",
			],
		},
		fallbackKind: "statistics_chart",
	}),
	template({
		id: "geography-9-vegetation-belts-map",
		title: "India natural vegetation belts map",
		description: "India outline with tropical evergreen / deciduous / desert / mangrove / montane forest belts highlighted.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["natural vegetation", "tropical evergreen", "tropical deciduous", "thorn forest", "montane forest", "mangrove", "bio reserve", "flora", "fauna"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["highlightedStates"],
			optionalSlots: ["mapStyle"],
			constraints: [
				"Highlight only the vegetation belts named in the stem.",
				"Caption must not state the vegetation type when identification is the question.",
			],
		},
		fallbackKind: "map_visual",
	}),
	template({
		id: "history-9-french-revolution-timeline",
		title: "French Revolution timeline",
		description: "1789–1799 events: Estates-General, Bastille, Declaration of Rights of Man, Reign of Terror, Directory.",
		subjects: ["History", "Social Science"],
		topicTags: ["french revolution", "estates general", "bastille", "declaration of rights of man", "jacobin", "reign of terror", "directory", "louis xvi", "robespierre", "olympe de gouges"],
		gradeBands: ["9-10"],
		kind: "timeline",
		priority: "essential",
		slotContract: {
			requiredSlots: ["events", "title"],
			optionalSlots: ["axisLabel"],
			constraints: [
				"Events must follow chronological order unless reordering is the question.",
				"Caption must not state which event came first when ordering is assessed.",
			],
		},
	}),
	template({
		id: "history-9-russian-revolution-timeline",
		title: "Russian Revolution timeline",
		description: "1905–1924 events: Bloody Sunday, Duma, February Revolution, October Revolution, Civil War, USSR formation.",
		subjects: ["History", "Social Science"],
		topicTags: ["russian revolution", "tsar", "bolshevik", "menshevik", "february revolution", "october revolution", "lenin", "duma", "soviet", "bloody sunday", "petrograd", "civil war"],
		gradeBands: ["9-10"],
		kind: "timeline",
		priority: "essential",
		slotContract: {
			requiredSlots: ["events", "title"],
			optionalSlots: ["axisLabel"],
			constraints: [
				"Distinguish February and October events on the same axis.",
				"Caption must not state which revolution preceded the other when ordering is assessed.",
			],
		},
	}),
	template({
		id: "history-9-nazism-source-extract",
		title: "Nazism source extract",
		description: "Line-numbered passage from Hitler's writings or contemporary accounts for source-analysis stems.",
		subjects: ["History", "Social Science"],
		topicTags: ["nazism", "hitler", "third reich", "mein kampf", "weimar republic", "aryan", "lebensraum", "propaganda", "holocaust", "world war ii"],
		gradeBands: ["9-10"],
		kind: "source_extract",
		priority: "essential",
		slotContract: {
			requiredSlots: ["lines"],
			optionalSlots: ["title", "source", "context"],
			constraints: [
				"Line numbers in the stem must exist in the extract.",
				"Do not paraphrase the answer in caption or altText.",
			],
		},
		fallbackKind: "english_passage",
	}),
	template({
		id: "civics-9-working-of-institutions-flow",
		title: "Government institutions working flow",
		description: "Flowchart relating Parliament, Executive (PM/President/Cabinet), and Judiciary for decision-flow and powers-allocation stems.",
		subjects: ["Civics", "Social Science"],
		topicTags: ["working of institutions", "parliament", "lok sabha", "rajya sabha", "president", "prime minister", "cabinet", "judiciary", "supreme court", "office memorandum", "mandal commission"],
		gradeBands: ["9-10"],
		kind: "flowchart",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["nodes", "edges"],
			optionalSlots: ["decisionLabels", "outcomes"],
			constraints: [
				"Edges must show direction of authority or decision flow.",
				"Caption must not state which institution performs the function being asked.",
			],
		},
	}),
	template({
		id: "geography-india-resources-grade-10",
		title: "India resources / soils map (Grade 10)",
		description: "India political-or-thematic map highlighting soil-type or resource-distribution regions.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["resources and development", "soil", "alluvial", "black soil", "red and yellow soil", "laterite", "land use", "resource distribution"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "essential",
		slotContract: {
			requiredSlots: ["mapStyle", "highlightedStates"],
			optionalSlots: [],
			constraints: [
				"`highlightedStates` ids must come from the india-map state code list (e.g. `mh`, `gj`, `rj`).",
				"Do not write the answer (soil type / resource name) into the alt text.",
			],
		},
		fallbackKind: "map_visual",
	}),
	template({
		id: "geography-india-water-grade-10",
		title: "India water resources map (Grade 10)",
		description: "India map highlighting multi-purpose river-project regions or major river basins.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["water resources", "multi purpose river project", "bhakra nangal", "sardar sarovar", "tehri", "river basin", "hirakud", "narmada", "rainwater harvesting"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "essential",
		slotContract: {
			requiredSlots: ["mapStyle", "highlightedStates"],
			optionalSlots: [],
			constraints: [
				"Highlight only the states the project / river basin spans.",
				"Do not place the project's name in the alt text when the question asks students to identify it.",
			],
		},
		fallbackKind: "map_visual",
	}),
	template({
		id: "geography-india-minerals-grade-10",
		title: "India minerals / energy map (Grade 10)",
		description: "India map highlighting iron / coal / bauxite / oilfield / nuclear-power locations.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["minerals and energy resources", "iron ore", "coal", "bauxite", "manganese", "petroleum", "nuclear power", "thermal power", "ferrous minerals"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "essential",
		slotContract: {
			requiredSlots: ["mapStyle", "highlightedStates"],
			optionalSlots: [],
			constraints: [
				"Highlight the producing states only; non-producing states stay default.",
				"Do not name the mineral / energy source in the alt text when identification is being assessed.",
			],
		},
		fallbackKind: "map_visual",
	}),
	template({
		id: "geography-india-industries-grade-10",
		title: "India manufacturing industries map (Grade 10)",
		description: "India map highlighting iron-steel, cotton-textile, sugar, IT, or petrochemical industrial regions.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["manufacturing industries", "iron steel", "cotton textile", "sugar industry", "petrochemical", "information technology", "industrial region", "agro based"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "essential",
		slotContract: {
			requiredSlots: ["mapStyle", "highlightedStates"],
			optionalSlots: [],
			constraints: [
				"Highlighted states must be the principal producing region for the industry referenced.",
				"Alt text describes geography only — no industrial output figures unless given by the stem.",
			],
		},
		fallbackKind: "map_visual",
	}),
	template({
		id: "geography-india-lifelines-grade-10",
		title: "India lifelines (transport) map (Grade 10)",
		description: "India map highlighting golden quadrilateral, major railway zones, major sea ports, or international airports.",
		subjects: ["Geography", "Social Science"],
		topicTags: ["lifelines of national economy", "transport", "roadways", "railways", "pipelines", "waterways", "airways", "golden quadrilateral", "sea ports"],
		gradeBands: ["9-10"],
		kind: "india_map",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["mapStyle", "highlightedStates"],
			optionalSlots: [],
			constraints: [
				"Highlight only states the corridor / port serves.",
				"Do not write the corridor / port name in alt text when identification is being assessed.",
			],
		},
		fallbackKind: "map_visual",
	}),
	template({
		id: "history-nationalism-europe-timeline-grade-10",
		title: "Rise of nationalism in Europe timeline (Grade 10)",
		description: "Chronological events 1789–1871: French Revolution, Congress of Vienna, 1830 & 1848 revolutions, unification of Germany and Italy.",
		subjects: ["History", "Social Science"],
		topicTags: ["rise of nationalism in europe", "french revolution", "congress of vienna", "1848 revolution", "unification of germany", "unification of italy", "mazzini", "bismarck", "cavour"],
		gradeBands: ["9-10"],
		kind: "timeline",
		priority: "essential",
		slotContract: {
			requiredSlots: ["title", "events"],
			optionalSlots: ["axisLabel"],
			constraints: [
				"Events must be in chronological order (1789 → 1871) unless the question asks students to reorder them.",
				"`dateLabel` should be the four-digit year and `label` the event name.",
			],
		},
	}),
	template({
		id: "history-nationalism-india-timeline-grade-10",
		title: "Nationalism in India timeline (Grade 10)",
		description: "Chronological events 1915–1947: Champaran, Rowlatt Act, Non-Cooperation, Civil Disobedience, Quit India.",
		subjects: ["History", "Social Science"],
		topicTags: ["nationalism in india", "khilafat", "non cooperation movement", "rowlatt act", "jallianwala bagh", "civil disobedience", "salt march", "dandi", "quit india", "champaran"],
		gradeBands: ["9-10"],
		kind: "timeline",
		priority: "essential",
		slotContract: {
			requiredSlots: ["title", "events"],
			optionalSlots: ["axisLabel"],
			constraints: [
				"Events must follow Gandhi-led movement chronology (1915 onwards) unless the question asks for reorder.",
				"Use the four-digit year as `dateLabel`.",
			],
		},
	}),
	template({
		id: "history-print-culture-source-grade-10",
		title: "Print culture source extract (Grade 10)",
		description: "Primary-source extract (Gutenberg, Luther, vernacular press, Raja Rammohan Roy) for source-based comprehension.",
		subjects: ["History", "Social Science"],
		topicTags: ["print culture and the modern world", "gutenberg", "printing press", "vernacular press", "luther", "reformation", "censorship", "newspapers"],
		gradeBands: ["9-10"],
		kind: "source_extract",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["lines"],
			optionalSlots: ["title", "source", "context"],
			constraints: [
				"Lines must be numbered starting at 1.",
				"Do not summarize the source's argument in `context` — students must infer it from the text.",
			],
		},
		fallbackKind: "english_passage",
	}),
	template({
		id: "civics-federalism-structure-grade-10",
		title: "Indian federalism structure (Grade 10)",
		description: "Three-tier flowchart of Union / State / Local government with the subject lists each tier legislates on.",
		subjects: ["Civics", "Social Science"],
		topicTags: ["federalism", "union government", "state government", "local government", "union list", "state list", "concurrent list", "panchayat", "municipality", "decentralisation"],
		gradeBands: ["9-10"],
		kind: "flowchart",
		priority: "essential",
		slotContract: {
			requiredSlots: ["title", "nodes", "edges"],
			optionalSlots: [],
			constraints: [
				"Top-level node must be the Union; child nodes are State and then Local (Panchayat / Municipality).",
				"Edge labels may name the legislative list ('Union list', 'State list', 'Concurrent list') only when the question is not about identifying the list.",
			],
		},
	}),
	template({
		id: "civics-power-sharing-grade-10",
		title: "Power-sharing models flowchart (Grade 10)",
		description: "Side-by-side flowchart comparing the Belgian accommodation model and the Sri Lankan majoritarian model.",
		subjects: ["Civics", "Social Science"],
		topicTags: ["power sharing", "belgium", "sri lanka", "majoritarianism", "accommodation", "ethnic conflict", "linguistic groups", "tamil", "sinhala"],
		gradeBands: ["9-10"],
		kind: "flowchart",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["title", "nodes", "edges"],
			optionalSlots: [],
			constraints: [
				"Two parallel branches — one for Belgium, one for Sri Lanka.",
				"Outcome nodes ('stability' / 'civil war') should not be pre-labelled if the question is about consequence-comparison.",
			],
		},
	}),
	template({
		id: "civics-political-parties-table-grade-10",
		title: "Political parties comparison table (Grade 10)",
		description: "Table comparing national and state political parties on recognition criteria, symbol, base region, and seat share.",
		subjects: ["Civics", "Social Science"],
		topicTags: ["political parties", "national party", "state party", "recognised", "symbol", "two party", "multi party", "election commission", "regional party"],
		gradeBands: ["9-10"],
		kind: "data_table",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption"],
			constraints: [
				"Headers should include 'Party', 'Type (National/State)', and any other criterion the question references (symbol, seat share).",
				"Do not mark the answer cell bold — the stem must drive identification.",
			],
		},
	}),
];
