import type { VisualTemplateDefinition } from "./shared";
import { template } from "./shared";

export const MATHEMATICS_VISUAL_TEMPLATES: VisualTemplateDefinition[] = [
	template({
		id: "math-coordinate-geometry",
		title: "Coordinate geometry construction",
		description: "Labelled points, segments, distances, and slopes on a coordinate plane.",
		subjects: ["Mathematics"],
		topicTags: ["coordinate", "distance", "midpoint", "section", "slope", "geometry"],
		gradeBands: ["9-10", "11-12"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["points", "segments", "view"],
			optionalSlots: ["angleMarkers", "circles", "labels"],
			constraints: ["All point labels in the stem must appear in the diagram.", "Use integer coordinates when possible."],
		},
	}),
	template({
		id: "math-function-graph",
		title: "Function graph",
		description: "Single or multi-curve graph with labelled axes and bounded domain.",
		subjects: ["Mathematics", "Statistics"],
		topicTags: ["function", "polynomial", "quadratic", "linear", "graph", "calculus"],
		gradeBands: ["9-10", "11-12"],
		kind: "math_function_plot",
		priority: "essential",
		slotContract: {
			requiredSlots: ["expression", "xRange", "axisLabels"],
			optionalSlots: ["yRange", "tickSteps", "legend"],
			constraints: ["Expressions must use renderer-supported syntax.", "Do not plot decorative curves unrelated to the question."],
		},
	}),
	template({
		id: "math-number-line-interval",
		title: "Number line interval",
		description: "Intervals, open and closed endpoints, and labelled critical points.",
		subjects: ["Mathematics"],
		topicTags: ["number line", "inequality", "sets", "interval"],
		gradeBands: ["6-8", "9-10", "11-12"],
		kind: "number_line",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["min", "max", "tickStep", "intervals"],
			optionalSlots: ["points", "axisLabel", "minorTicks"],
			constraints: ["Endpoint openness must match the solution set exactly."],
		},
	}),
	template({
		id: "math-9-polynomial-factor-graph",
		title: "Polynomial zeros on x-axis",
		description: "Polynomial curve with x-intercepts labelled to anchor factor-theorem stems.",
		subjects: ["Mathematics"],
		topicTags: ["polynomial", "factor theorem", "zeros", "zeroes of a polynomial", "remainder theorem", "factorisation"],
		gradeBands: ["9-10"],
		kind: "math_function_plot",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["expression", "xRange", "axisLabels"],
			optionalSlots: ["yRange", "tickSteps", "markers"],
			constraints: [
				"X-intercepts must be the zeros under test; do not highlight extras.",
				"Caption must not state the factor count.",
			],
		},
	}),
	template({
		id: "math-9-coordinate-quadrants",
		title: "Cartesian quadrants and point placement",
		description: "Coordinate plane with labelled axes, quadrants, and a small set of plotted points.",
		subjects: ["Mathematics"],
		topicTags: ["coordinate geometry", "cartesian plane", "quadrant", "abscissa", "ordinate", "x axis", "y axis"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["points", "view"],
			optionalSlots: ["labels", "segments"],
			constraints: [
				"Plot only the points referenced in the stem.",
				"Caption must not state which quadrant a point lies in if that is the question.",
			],
		},
	}),
	template({
		id: "math-9-linear-equation-line-graph",
		title: "Linear equation in two variables — line graph",
		description: "Single or paired lines representing ax + by + c = 0 with labelled axes.",
		subjects: ["Mathematics"],
		topicTags: ["linear equation", "linear equations in two variables", "two variables", "line graph", "ax by c", "solution of a linear equation"],
		gradeBands: ["9-10"],
		kind: "math_function_plot",
		priority: "essential",
		slotContract: {
			requiredSlots: ["expression", "xRange", "axisLabels"],
			optionalSlots: ["yRange", "tickSteps", "legend"],
			constraints: [
				"Lines must intersect inside the visible view when intersection is the question.",
				"Caption must not state the intersection coordinates.",
			],
		},
	}),
	template({
		id: "math-9-parallel-lines-transversal",
		title: "Parallel lines cut by a transversal",
		description: "Two parallel lines crossed by a transversal with labelled angles for angle-chase stems.",
		subjects: ["Mathematics"],
		topicTags: ["lines and angles", "parallel lines", "transversal", "corresponding angles", "alternate angles", "co interior", "linear pair"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["points", "segments", "angleMarkers", "view"],
			optionalSlots: ["labels"],
			constraints: [
				"Mark only the angles named in the stem; leave the unknown unmarked.",
				"Indicate parallel sides with matching arrows on the segments.",
			],
		},
	}),
	template({
		id: "math-9-triangle-congruence",
		title: "Triangle with congruence marks",
		description: "Two triangles or one triangle with tick marks on equal sides and arc marks on equal angles for SSS/SAS/ASA/RHS stems.",
		subjects: ["Mathematics"],
		topicTags: ["triangles", "congruence", "sss", "sas", "asa", "rhs", "isosceles triangle", "median", "perpendicular bisector"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["points", "segments", "view"],
			optionalSlots: ["angleMarkers", "labels"],
			constraints: [
				"Tick marks must match the equal-segment claim exactly.",
				"Caption must not name the congruence criterion when the criterion is the question.",
			],
		},
	}),
	template({
		id: "math-9-quadrilateral-properties",
		title: "Quadrilateral with diagonals",
		description: "Parallelogram, rhombus, rectangle, square, or trapezium with diagonals and mid-points for property proofs.",
		subjects: ["Mathematics"],
		topicTags: ["quadrilaterals", "parallelogram", "rhombus", "rectangle", "square", "trapezium", "diagonals", "mid point theorem"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["points", "segments", "view"],
			optionalSlots: ["angleMarkers", "labels"],
			constraints: [
				"Label all four vertices in cyclic order matching the stem.",
				"Indicate equal sides or right angles only where the stem already establishes them.",
			],
		},
	}),
	template({
		id: "math-9-circle-chord-arc",
		title: "Circle with chord, arc, and subtended angle",
		description: "Circle with centre, chord, and one or more inscribed or central angles for cyclic quadrilateral and chord-angle stems.",
		subjects: ["Mathematics"],
		topicTags: ["circles", "chord", "arc", "cyclic quadrilateral", "angle subtended", "centre of circle", "inscribed angle"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["points", "circles", "view"],
			optionalSlots: ["segments", "angleMarkers", "labels"],
			constraints: [
				"Centre O must be marked when the question references a central angle.",
				"Caption must not state which arc is major or minor when that is the question.",
			],
		},
	}),
	template({
		id: "math-9-heron-triangle-sides",
		title: "Triangle with labelled side lengths",
		description: "Triangle drawn with three explicit side lengths labelled, for Heron's-formula area stems.",
		subjects: ["Mathematics"],
		topicTags: ["heron formula", "herons formula", "area of triangle", "semi perimeter", "side lengths", "triangular"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["points", "segments", "view"],
			optionalSlots: ["labels"],
			constraints: [
				"All three side-length labels must appear next to the correct segment.",
				"Caption must not state the area or semi-perimeter.",
			],
		},
	}),
	template({
		id: "math-9-statistics-grouped-histogram",
		title: "Grouped-frequency histogram",
		description: "Histogram or frequency polygon over class intervals for Class 9 Statistics grouped-data stems.",
		subjects: ["Mathematics"],
		topicTags: ["statistics", "grouped frequency", "class interval", "histogram", "frequency polygon", "bar graph", "class mark"],
		gradeBands: ["9-10"],
		kind: "statistics_chart",
		priority: "essential",
		slotContract: {
			requiredSlots: ["subKind", "data"],
			optionalSlots: ["axisLabels", "callouts"],
			constraints: [
				"Class intervals must be equal width unless the chapter explicitly varies them.",
				"Caption must not state the modal class.",
			],
		},
	}),
	template({
		id: "math-polynomial-zeroes-grade-10",
		title: "Polynomial zeroes graph (Grade 10)",
		description: "Polynomial curve crossing the x-axis at its real zeroes.",
		subjects: ["Mathematics"],
		topicTags: ["polynomial", "zeroes", "geometrical meaning", "parabola", "cubic", "degree", "real roots"],
		gradeBands: ["9-10"],
		kind: "math_function_plot",
		priority: "essential",
		slotContract: {
			requiredSlots: ["items", "xMin", "xMax", "xLabel", "yLabel"],
			optionalSlots: ["yMin", "yMax", "xTickStep", "yTickStep"],
			constraints: [
				"The curve must cross the x-axis exactly at the polynomial's real zeroes referenced in the stem.",
				"Do not write the zero values as labels — students must read them off the graph.",
			],
		},
	}),
	template({
		id: "math-linear-equations-pair-grade-10",
		title: "Pair of linear equations graph (Grade 10)",
		description: "Two straight lines on the same axes showing intersection, parallelism, or coincidence.",
		subjects: ["Mathematics"],
		topicTags: ["pair of linear equations", "graphical method", "two variables", "intersection", "consistent", "inconsistent", "lines"],
		gradeBands: ["9-10"],
		kind: "math_function_plot",
		priority: "essential",
		slotContract: {
			requiredSlots: ["items", "xMin", "xMax", "xLabel", "yLabel"],
			optionalSlots: ["yMin", "yMax", "xTickStep", "yTickStep"],
			constraints: [
				"Draw exactly two lines; label each with its equation.",
				"The geometric relationship (intersecting / parallel / coincident) must match the algebraic answer.",
			],
		},
	}),
	template({
		id: "math-quadratic-parabola-grade-10",
		title: "Quadratic parabola (Grade 10)",
		description: "Parabola showing the quadratic's roots and opening direction.",
		subjects: ["Mathematics"],
		topicTags: ["quadratic equation", "parabola", "roots", "nature of roots", "discriminant", "vertex", "axis of symmetry"],
		gradeBands: ["9-10"],
		kind: "math_function_plot",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["items", "xMin", "xMax", "xLabel", "yLabel"],
			optionalSlots: ["yMin", "yMax"],
			constraints: [
				"Plot a single parabola y = ax² + bx + c with opening matching sign(a).",
				"Mark roots only if the question asks students to count or identify them; otherwise leave unlabelled.",
			],
		},
	}),
	template({
		id: "math-triangle-similarity-grade-10",
		title: "Triangle similarity / BPT figure (Grade 10)",
		description: "Two similar triangles or a triangle with a parallel-line transversal for the Basic Proportionality Theorem.",
		subjects: ["Mathematics"],
		topicTags: ["triangles", "similarity", "basic proportionality theorem", "bpt", "thales", "aa criterion", "sas criterion", "sss criterion"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["view", "primitives"],
			optionalSlots: [],
			constraints: [
				"Label vertices clearly; mark corresponding equal angles with the same number of arcs.",
				"For BPT, draw the dividing segment dashed and label the four sub-segment lengths.",
			],
		},
	}),
	template({
		id: "math-pythagoras-right-triangle-grade-10",
		title: "Pythagoras right triangle (Grade 10)",
		description: "Right triangle with labelled legs and hypotenuse and the right-angle marker.",
		subjects: ["Mathematics"],
		topicTags: ["triangles", "pythagoras theorem", "right triangle", "hypotenuse", "perpendicular", "base"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["view", "primitives"],
			optionalSlots: [],
			constraints: [
				"Mark the right angle with a small square at the correct vertex.",
				"Label any two of the three sides with their numeric lengths; the unknown side stays unlabelled.",
			],
		},
	}),
	template({
		id: "math-trigonometry-right-triangle-grade-10",
		title: "Trigonometry right triangle (Grade 10)",
		description: "Right triangle with the reference angle and opposite / adjacent / hypotenuse positions called out.",
		subjects: ["Mathematics"],
		topicTags: ["introduction to trigonometry", "trigonometric ratios", "sine", "cosine", "tangent", "right triangle", "opposite", "adjacent", "hypotenuse"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["view", "primitives"],
			optionalSlots: [],
			constraints: [
				"Mark the right angle and the reference angle (θ) explicitly.",
				"Do not name a ratio in any label — students must compute sin / cos / tan from the figure.",
			],
		},
	}),
	template({
		id: "math-heights-distances-grade-10",
		title: "Heights and distances figure (Grade 10)",
		description: "Vertical object (pole, tower, building) with horizontal ground, angle of elevation / depression, and the line of sight.",
		subjects: ["Mathematics"],
		topicTags: ["heights and distances", "applications of trigonometry", "angle of elevation", "angle of depression", "line of sight", "tower", "building"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["view", "primitives"],
			optionalSlots: [],
			constraints: [
				"Draw the ground as a horizontal segment and the object as a vertical segment meeting at a right angle.",
				"Mark the angle of elevation or depression with an arc and its numeric value (e.g. 30°, 45°, 60°).",
			],
		},
	}),
	template({
		id: "math-circle-tangent-grade-10",
		title: "Circle tangent figure (Grade 10)",
		description: "Circle with a tangent line, the radius to the point of contact, and any chord or external point referenced in the stem.",
		subjects: ["Mathematics"],
		topicTags: ["circles", "tangent", "chord", "point of contact", "radius", "external point", "secant"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "essential",
		slotContract: {
			requiredSlots: ["view", "primitives"],
			optionalSlots: [],
			constraints: [
				"Draw the radius to the point of contact and mark the 90° angle between radius and tangent.",
				"Every named point in the stem (P, Q, O, T, …) must appear with the same label in the figure.",
			],
		},
	}),
	template({
		id: "math-circle-sector-segment-grade-10",
		title: "Circle sector or segment (Grade 10)",
		description: "Circle with a sector or segment highlighted and the central angle labelled.",
		subjects: ["Mathematics"],
		topicTags: ["areas related to circles", "sector", "segment", "central angle", "minor", "major", "arc"],
		gradeBands: ["9-10"],
		kind: "math_geometry",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["view", "primitives"],
			optionalSlots: [],
			constraints: [
				"Shade or dash the requested region (sector / minor segment / major segment) without numeric area labels.",
				"Mark the central angle with an arc and its value (e.g. 60°, 90°, 120°).",
			],
		},
	}),
	template({
		id: "math-statistics-ogive-grade-10",
		title: "Statistics ogive (Grade 10)",
		description: "Less-than or more-than ogive built from a grouped frequency distribution.",
		subjects: ["Mathematics", "Statistics"],
		topicTags: ["statistics", "ogive", "cumulative frequency", "less than", "more than", "grouped data", "median"],
		gradeBands: ["9-10"],
		kind: "statistics_chart",
		priority: "essential",
		slotContract: {
			requiredSlots: ["subKind", "bins", "cumulative", "xLabel", "yLabel"],
			optionalSlots: [],
			constraints: [
				"`subKind` must be `ogive` and `cumulative` must match the question (`less_than` or `more_than`).",
				"Bin upper boundaries (or lower boundaries for more-than) must match the class intervals in the stem.",
			],
		},
	}),
];
