import type { VisualTemplateDefinition } from "./shared";
import { template } from "./shared";

export const SCIENCE_VISUAL_TEMPLATES: VisualTemplateDefinition[] = [
	template({
		id: "science-classification-table",
		title: "Science classification table",
		description: "Comparison or classification table for general science concepts.",
		subjects: ["Science"],
		topicTags: ["classification", "comparison", "properties", "observation", "experiment", "table"],
		gradeBands: ["6-8", "9-10"],
		kind: "data_table",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption", "boldCells"],
			constraints: ["The table should contain the stimulus, not duplicate all information in the stem."],
		},
	}),
	template({
		id: "science-9-separation-flowchart",
		title: "Separation-technique decision flow",
		description: "Flowchart that branches by mixture type (solid-liquid, liquid-liquid, etc.) to a named separation method.",
		subjects: ["Science", "Chemistry"],
		topicTags: ["separation", "mixture", "filtration", "evaporation", "distillation", "chromatography", "centrifugation", "sublimation"],
		gradeBands: ["9-10"],
		kind: "flowchart",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["nodes", "edges"],
			optionalSlots: ["decisionLabels", "outcomes"],
			constraints: [
				"Terminal nodes must be technique names, not properties.",
				"Do not place the answer at a leaf node when identification is assessed.",
			],
		},
	}),
	template({
		id: "science-9-atom-mass-conservation-table",
		title: "Atomic mass and conservation table",
		description: "Tabular stimulus for atomic masses, valencies, or reactant-product mass tallies.",
		subjects: ["Science", "Chemistry"],
		topicTags: ["atoms and molecules", "atomic mass", "valency", "conservation of mass", "law of constant proportions", "mole concept"],
		gradeBands: ["9-10"],
		kind: "data_table",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption", "boldCells"],
			constraints: [
				"Totals must reconcile when the question asks students to verify conservation.",
				"Leave only the assessed cells blank.",
			],
		},
		fallbackKind: "chemistry_reaction",
	}),
	template({
		id: "science-9-atomic-shell-distribution",
		title: "K/L/M electron-shell distribution",
		description: "Tabular stimulus for shell distributions, atomic numbers, mass numbers, and isotope comparisons.",
		subjects: ["Science", "Chemistry"],
		topicTags: ["structure of the atom", "atomic number", "mass number", "electron shell", "k l m shells", "isotope", "isobar", "bohr model"],
		gradeBands: ["9-10"],
		kind: "data_table",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption", "boldCells"],
			constraints: [
				"Shell-occupancy rows must obey 2n² where the chapter applies it.",
				"Leave the assessed cell blank without revealing it in caption.",
			],
		},
	}),
	template({
		id: "science-9-cell-organelle-diagram",
		title: "Labelled cell organelle diagram",
		description: "Cell cross-section with organelle labels for plant/animal cell identification stems.",
		subjects: ["Science", "Biology"],
		topicTags: ["cell", "plasma membrane", "nucleus", "mitochondria", "endoplasmic reticulum", "ribosome", "lysosome", "plastid", "vacuole", "eukaryotic", "prokaryotic"],
		gradeBands: ["9-10"],
		kind: "biology_diagram",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["subKind", "labels", "title"],
			optionalSlots: ["notes"],
			constraints: [
				"Label only the organelles referenced in the stem.",
				"Caption must not state the organelle function being asked.",
			],
		},
		fallbackKind: "data_table",
	}),
	template({
		id: "science-9-tissues-comparison",
		title: "Plant and animal tissue panel",
		description: "Tissue cross-section or comparative panel for parenchyma, collenchyma, epithelial, connective, muscular, and nervous tissue stems.",
		subjects: ["Science", "Biology"],
		topicTags: ["tissues", "parenchyma", "collenchyma", "sclerenchyma", "xylem", "phloem", "epithelial", "connective tissue", "muscular tissue", "nervous tissue", "meristem"],
		gradeBands: ["9-10"],
		kind: "biology_diagram",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["subKind", "labels", "title"],
			optionalSlots: ["notes"],
			constraints: [
				"Labels must use NCERT tissue vocabulary verbatim.",
				"Caption must not name the tissue when identification is the question.",
			],
		},
		fallbackKind: "data_table",
	}),
	template({
		id: "science-9-motion-velocity-time-graph",
		title: "Velocity-time or distance-time graph",
		description: "Single-axis kinematic graph for uniform, uniformly accelerated, and decelerated motion.",
		subjects: ["Science", "Physics"],
		topicTags: ["motion", "displacement", "velocity", "acceleration", "uniform motion", "velocity time graph", "distance time graph", "average speed"],
		gradeBands: ["9-10"],
		kind: "math_function_plot",
		priority: "essential",
		slotContract: {
			requiredSlots: ["expression", "xRange", "axisLabels"],
			optionalSlots: ["yRange", "tickSteps", "markers"],
			constraints: [
				"X-axis must be labelled with time and a unit; y-axis with the kinematic quantity.",
				"Caption must not state the slope value when slope is the question.",
			],
		},
	}),
	template({
		id: "science-9-free-body-motion-laws",
		title: "Free-body diagram for Newton's laws",
		description: "Single object with labelled force vectors for applied-force, friction, normal, weight, and tension stems.",
		subjects: ["Science", "Physics"],
		topicTags: ["force", "laws of motion", "inertia", "newton first law", "newton second law", "newton third law", "balanced forces", "unbalanced forces", "friction"],
		gradeBands: ["9-10"],
		kind: "physics_diagram",
		priority: "essential",
		slotContract: {
			requiredSlots: ["subKind", "objects", "forces"],
			optionalSlots: ["labels", "title"],
			constraints: [
				"Force arrows must start at the object and point outward.",
				"Do not draw a net-force arrow when the net force is the question.",
			],
		},
	}),
	template({
		id: "science-9-work-energy-diagram",
		title: "Force-displacement work diagram",
		description: "Object with applied force vector and displacement direction for positive/negative/zero work questions.",
		subjects: ["Science", "Physics"],
		topicTags: ["work", "energy", "kinetic energy", "potential energy", "work done by force", "displacement direction"],
		gradeBands: ["9-10"],
		kind: "physics_diagram",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["subKind", "objects", "forces"],
			optionalSlots: ["labels", "title"],
			constraints: [
				"Displacement arrow must be drawn separately from the force arrow.",
				"Caption must not state the sign of work.",
			],
		},
	}),
	template({
		id: "science-9-sound-wave-form",
		title: "Longitudinal sound wave",
		description: "Compression-rarefaction wave with labelled wavelength and amplitude for Class 9 Sound stems.",
		subjects: ["Science", "Physics"],
		topicTags: ["sound", "longitudinal wave", "compression", "rarefaction", "wavelength", "frequency", "pitch", "loudness", "ultrasound"],
		gradeBands: ["9-10"],
		kind: "physics_wave_diagram",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["waveType", "xRange", "amplitude"],
			optionalSlots: ["wavelength", "markers"],
			constraints: [
				"Wave type must be longitudinal for compression/rarefaction stems.",
				"Caption must not state the frequency value being asked.",
			],
		},
	}),
	template({
		id: "science-chemical-reaction-types-grade-10",
		title: "Chemical reaction with type (Grade 10)",
		description: "Balanced chemical equation with state symbols and (optional) conditions, illustrating combination, decomposition, displacement, or double displacement.",
		subjects: ["Science", "Chemistry"],
		topicTags: ["chemical reactions and equations", "combination reaction", "decomposition reaction", "displacement reaction", "double displacement", "state symbols", "balanced equation"],
		gradeBands: ["9-10"],
		kind: "chemistry_reaction",
		priority: "essential",
		slotContract: {
			requiredSlots: ["ce"],
			optionalSlots: ["label"],
			constraints: [
				"Use mhchem syntax with explicit state symbols (s), (l), (g), (aq).",
				"Equation must be balanced for both atoms and charge.",
				"Do not state the reaction type in the label if the question asks students to identify it.",
			],
		},
	}),
	template({
		id: "science-ph-scale-grade-10",
		title: "pH scale table (Grade 10)",
		description: "Reference table mapping pH values to common substances and acid/base/neutral classification.",
		subjects: ["Science", "Chemistry"],
		topicTags: ["acids bases and salts", "ph scale", "indicator", "acidic", "basic", "neutral", "hydrogen ion concentration"],
		gradeBands: ["9-10"],
		kind: "data_table",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption"],
			constraints: [
				"Headers should include at least 'Substance' and 'pH'; rows should span both acidic (pH < 7) and basic (pH > 7) regions.",
				"Do not pre-classify the asked-about substance as acidic / basic / neutral.",
			],
		},
	}),
	template({
		id: "science-reactivity-series-grade-10",
		title: "Reactivity series table (Grade 10)",
		description: "Reactivity-series comparison table ordering common metals from most to least reactive.",
		subjects: ["Science", "Chemistry"],
		topicTags: ["metals and non-metals", "reactivity series", "displacement", "thermite", "potassium", "sodium", "iron", "copper", "gold"],
		gradeBands: ["9-10"],
		kind: "data_table",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["headers", "rows"],
			optionalSlots: ["caption"],
			constraints: [
				"Order rows from most reactive (top) to least reactive (bottom) unless the question asks for the reverse.",
				"Do not include the metal being asked about as boldface unless the answer is independent of position.",
			],
		},
	}),
	template({
		id: "science-carbon-functional-groups-grade-10",
		title: "Carbon compound structure (Grade 10)",
		description: "Structural formula of a Grade 10 carbon compound: alcohol, aldehyde, ketone, carboxylic acid, alkane, alkene, alkyne, or haloalkane.",
		subjects: ["Science", "Chemistry"],
		topicTags: ["carbon and its compounds", "functional group", "homologous series", "alcohol", "aldehyde", "carboxylic acid", "ketone", "alkane", "alkene", "structural isomer"],
		gradeBands: ["9-10"],
		kind: "chemistry_molecule",
		priority: "essential",
		slotContract: {
			requiredSlots: ["smiles"],
			optionalSlots: ["label", "display"],
			constraints: [
				"Use valid SMILES; molecule must be a 1-6 carbon compound from the Grade 10 syllabus.",
				"Do not name the functional group in the label when the question asks students to identify it.",
			],
		},
	}),
	template({
		id: "science-light-mirror-ray-grade-10",
		title: "Spherical mirror ray diagram (Grade 10)",
		description: "Concave or convex mirror ray diagram showing object, image, focal point, and centre of curvature.",
		subjects: ["Science", "Physics"],
		topicTags: ["light reflection and refraction", "spherical mirror", "concave mirror", "convex mirror", "focal length", "centre of curvature", "principal axis", "real image", "virtual image"],
		gradeBands: ["9-10"],
		kind: "physics_diagram",
		priority: "essential",
		slotContract: {
			requiredSlots: ["subKind", "axisMin", "axisMax", "objects", "lenses"],
			optionalSlots: ["axisUnit", "drawRays"],
			constraints: [
				"`subKind` must be `ray_optics` and `lenses[].type` must be `concave_mirror` or `convex_mirror`.",
				"Object distance, focal length, and image position must satisfy the mirror formula 1/v + 1/u = 1/f using the sign convention.",
			],
		},
	}),
	template({
		id: "science-light-lens-ray-grade-10",
		title: "Lens ray diagram (Grade 10)",
		description: "Concave or convex lens ray diagram showing object, image, focal points, and the principal axis.",
		subjects: ["Science", "Physics"],
		topicTags: ["light refraction", "lens", "convex lens", "concave lens", "focal length", "principal axis", "magnification", "image formation"],
		gradeBands: ["9-10"],
		kind: "physics_diagram",
		priority: "essential",
		slotContract: {
			requiredSlots: ["subKind", "axisMin", "axisMax", "objects", "lenses"],
			optionalSlots: ["axisUnit", "drawRays"],
			constraints: [
				"`subKind` must be `ray_optics` and `lenses[].type` must be `convex_lens` or `concave_lens`.",
				"Object and image positions must satisfy 1/v - 1/u = 1/f under the lens sign convention.",
			],
		},
	}),
	template({
		id: "science-human-eye-defects-grade-10",
		title: "Human eye defect and correction (Grade 10)",
		description: "Eye-defect ray diagram (myopia / hypermetropia / presbyopia) and the corrective lens that fixes it.",
		subjects: ["Science", "Physics"],
		topicTags: ["human eye", "defects of vision", "myopia", "hypermetropia", "presbyopia", "near point", "far point", "corrective lens"],
		gradeBands: ["9-10"],
		kind: "physics_diagram",
		priority: "recommended",
		slotContract: {
			requiredSlots: ["subKind", "axisMin", "axisMax", "objects", "lenses"],
			optionalSlots: ["axisUnit", "drawRays"],
			constraints: [
				"`subKind` must be `ray_optics`; show the corrective lens type that matches the defect.",
				"Do not label the defect name when the question asks for identification.",
			],
		},
	}),
	template({
		id: "science-circuit-series-parallel-grade-10",
		title: "Series / parallel circuit (Grade 10)",
		description: "Battery with resistors in series or parallel, optional ammeter / voltmeter / bulb / switch.",
		subjects: ["Science", "Physics"],
		topicTags: ["electricity", "ohm's law", "series resistor", "parallel resistor", "ammeter", "voltmeter", "potential difference", "current"],
		gradeBands: ["9-10"],
		kind: "physics_diagram",
		priority: "essential",
		slotContract: {
			requiredSlots: ["subKind", "nodes", "components"],
			optionalSlots: [],
			constraints: [
				"`subKind` must be `circuit`.",
				"Ammeter must be in series with the component whose current is measured; voltmeter must be in parallel.",
				"Resistor values, emf, and any visible meter reading must match the answer.",
			],
		},
	}),
	template({
		id: "science-magnetic-field-conductor-grade-10",
		title: "Magnetic field around conductor (Grade 10)",
		description: "Magnetic field lines around a current-carrying straight conductor, circular loop, or solenoid.",
		subjects: ["Science", "Physics"],
		topicTags: ["magnetic effects of electric current", "magnetic field lines", "current carrying conductor", "solenoid", "right hand rule", "north pole", "south pole"],
		gradeBands: ["9-10"],
		kind: "physics_field_diagram",
		priority: "essential",
		slotContract: {
			requiredSlots: ["fieldType", "title", "sources", "fieldLineCount"],
			optionalSlots: ["labels"],
			constraints: [
				"`fieldType` must be `magnetic`.",
				"Field-line arrows must match the right-hand rule for the current direction shown.",
			],
		},
		fallbackKind: "physics_diagram",
	}),
];
