import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

import { formatDateTimeMediumShortInAppTimeZone } from "@/lib/datetime/app-timezone";
import {
	formatDuration,
	formatScorePercent,
	type SubjectTestRowSerialized,
} from "@/lib/student/subject-test-report";

const styles = StyleSheet.create({
	page: {
		padding: 40,
		fontSize: 11,
		fontFamily: "Helvetica",
	},
	title: { fontSize: 18, marginBottom: 6, fontFamily: "Helvetica-Bold" },
	subtitle: { fontSize: 10, color: "#444", marginBottom: 16 },
	section: { marginTop: 12, marginBottom: 8 },
	row: { flexDirection: "row", marginBottom: 4 },
	label: { width: 120, color: "#555", fontFamily: "Helvetica-Bold" },
	value: { flex: 1 },
	note: {
		marginTop: 20,
		padding: 10,
		backgroundColor: "#f5f5f5",
		fontSize: 9,
		color: "#333",
	},
	footer: { position: "absolute", bottom: 28, left: 40, right: 40, fontSize: 8, color: "#888" },
});

function formatDate(iso: string | null | undefined): string {
	if (!iso) return "—";
	try {
		return formatDateTimeMediumShortInAppTimeZone(iso);
	} catch {
		return "—";
	}
}

export type TestReportPdfDocumentProps = {
	subjectName: string;
	test: SubjectTestRowSerialized;
	hasAiReport: boolean;
};

export function TestReportPdfDocument({ subjectName, test, hasAiReport }: TestReportPdfDocumentProps) {
	const correct = test.correctAnswers ?? 0;
	const totalQ = test.totalQuestions ?? 0;
	const qLine = totalQ > 0 ? `${correct} / ${totalQ}` : "—";

	return (
		<Document>
			<Page size="A4" style={styles.page}>
				<Text style={styles.title}>Test report</Text>
				<Text style={styles.subtitle}>
					{subjectName} · {formatDate(test.testDate ?? test.createdAt)}
				</Text>

				<View style={styles.section}>
					<View style={styles.row}>
						<Text style={styles.label}>Test ID</Text>
						<Text style={styles.value}>{test.id}</Text>
					</View>
					<View style={styles.row}>
						<Text style={styles.label}>Type</Text>
						<Text style={styles.value}>{test.testType ?? "—"}</Text>
					</View>
					<View style={styles.row}>
						<Text style={styles.label}>Status</Text>
						<Text style={styles.value}>{test.status ?? "—"}</Text>
					</View>
					<View style={styles.row}>
						<Text style={styles.label}>Unit</Text>
						<Text style={styles.value}>{test.unitName?.trim() ? test.unitName : "—"}</Text>
					</View>
					<View style={styles.row}>
						<Text style={styles.label}>Difficulty</Text>
						<Text style={styles.value}>{test.difficulty ?? "—"}</Text>
					</View>
					<View style={styles.row}>
						<Text style={styles.label}>Score</Text>
						<Text style={styles.value}>{formatScorePercent(test.totalScore)}</Text>
					</View>
					<View style={styles.row}>
						<Text style={styles.label}>Questions correct</Text>
						<Text style={styles.value}>{qLine}</Text>
					</View>
					<View style={styles.row}>
						<Text style={styles.label}>Duration</Text>
						<Text style={styles.value}>{formatDuration(test.durationSeconds)}</Text>
					</View>
					<View style={styles.row}>
						<Text style={styles.label}>Draft</Text>
						<Text style={styles.value}>{test.isDraft ? "Yes" : "No"}</Text>
					</View>
				</View>

				{!hasAiReport ? (
					<Text style={styles.note}>
						Full narrative report (strengths, gaps, and recommendations) will appear here when an
						AI report is generated for this test.
					</Text>
				) : (
					<Text style={styles.note}>AI summary is available in the app for this test.</Text>
				)}

				<Text style={styles.footer} fixed>
				Generated by 24Vertex · For your records only
				</Text>
			</Page>
		</Document>
	);
}
